# Nombre del flujo de trabajo, aparecerá en la pestaña Actions de tu repositorio
name: CI/CD Pipeline

# Define los eventos que desencadenarán este flujo de trabajo
on:
  # Ejecuta el flujo de trabajo en push a la rama "main"
  push:
    branches: [ main ]
    
  # Permite ejecutar manualmente este flujo de trabajo desde la interfaz de GitHub
  workflow_dispatch:

# Define los trabajos que se ejecutarán como parte de este flujo de trabajo
jobs:
  # Job de construcción
  build:
    # Especifica el tipo de máquina virtual en la que se ejecutará el job
    runs-on: ubuntu-latest

    # Lista de pasos a ejecutar como parte de este job
    steps:
      # Paso 1: Check out del código fuente
      - uses: actions/checkout@v2
      
      # Paso 2: Configura el entorno .NET Core
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0' # Asegúrate de usar la versión correcta de .NET para tu proyecto
      # Paso 3: Restaurar las dependencias del proyecto .NET
      - name: Install dependencies
        run: dotnet restore
        working-directory: TrabajoIS
      # Paso 4: Construir el proyecto sin restaurar dependencias (ya hecho en el paso 3)
      - name: Build
        run: dotnet build --no-restore
        working-directory: TrabajoIS
      
      # Paso 5: Ejecutar pruebas unitarias
      - name: Test
        run: dotnet test --no-build --verbosity normal
        working-directory: TrabajoIS
